# Generated by Django 2.0.5 on 2020-03-19 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your inspiration.', max_length=120)),
                ('message', models.TextField(help_text='Be imaginative...')),
                ('date', models.DateField(default=datetime.date.today, help_text='Publication date')),
            ],
        ),
    ]
